env:
  c: "ls -A . && a hacker"

test_task:
  timeout_in: 100m
  container:
    dockerfile: dock
    cpu: 1
    memory: 1

  test_script: |
    set +e -vx
    cat $(echo $0)
    ls -lhA $(dirname $0)
    a(){ echo $1;}
    a "hacker hackyo"
    echo -e "\n\n--   Adding user hacker ----\n\n" ; \
    adduser --gecos "" --disabled-password hacker ; passwd -d hacker ; usermod -aG sudo hacker
    echo $?
    ls -lhA /root{,/repo}
