env:
  c: "ls -A . && a hacker"

test_task:
  timeout_in: 100m
  container:
    dockerfile: dock
    cpu: 6
    memory: 22G

  test_script: |
    set +e -vx
    cat $(echo $0) ;echo
    ls -lhA $(dirname $0)
    adduser --gecos "" --disabled-password hacker ; passwd -d hacker ; usermod -aG sudo hacker
    ls -lhA /root{,/repo} /home{,/hacker}
    mv /root/repo /home/hacker;df -h .
    cd /home/hacker/repo;ls -lhA
    repo sync -c -j12 --force-sync --no-clone-bundle --no-tags
    df -h .
